#!/usr/bin/env bash

set -x
set -o errexit

cabal configure --disable-tests

DOCDIR=`mktemp -d -t pages.XXXXXX`
standalone-haddock -o $DOCDIR --package-db .cabal-sandbox/x86_64-osx-ghc-7.6.3-packages.conf.d/ .

HEAD=`git rev-parse HEAD`

git checkout gh-pages
git rm -rf --ignore-unmatch .

mv $DOCDIR/* .
rm -rf dist/
git add ed-e *.html *.js *.css *.gif *.png

git commit -m "Generated documentation from $HEAD"
